[package]
name = "mailsync"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
csv = "1.0.0-beta.4"
email-parser = { path = "../email-parser" }
futures = "*"
futures-state-stream = "*"
itertools = "*"
mbox-reader = { path = "../mbox-reader" }
postgres = { git = "https://github.com/sfackler/rust-postgres", features = ["with-chrono"] }
postgres-derive = "0.3.1"
serde = "*"
serde_derive = "*"
tokio-core = "*"
tokio-imap = { path = "../tokio-imap/tokio-imap" }
tokio-postgres = { git = "https://github.com/sfackler/rust-postgres", features = ["with-chrono"] }
toml = "*"

[replace]
"futures-state-stream:0.1.1" = { path = "../futures-state-stream" }
