[package]
name = "mailsync"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]

[dependencies]
futures = "*"
serde = "*"
serde_derive = "*"
tokio-core = "*"
tokio-imap = { path = "../tokio-imap" }
toml = "*"
