[package]
name = "mailsync"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]

[dependencies]
futures = "*"
futures-state-stream = "*"
serde = "*"
serde_derive = "*"
tokio-core = "*"
tokio-imap = { path = "../tokio-imap" }
tokio-postgres = "*"
toml = "*"

[replace]
"futures-state-stream:0.1.1" = { path = "../futures-state-stream" }
